
server:
  port: 8080


spring:
  redis:
    host: 39.104.21.126
    port: 6379
    timeout: 3000 # 超时时间3000毫秒
    password: heihei
    lettuce:
      pool:
        max-active: 200 # 200个连接
        max-idle: 10 # 最多空闲10个连接
        max-wait: 8000  #最大等待 8000毫秒
        min-idle: 0  # 最小空闲
    databases:
      defaultDB: 0
      db1: 1
      db2: 2
      db3: 3

